spring.application.name=controleestoque
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
api.security.token.secret=${JWT_SECRET:my-secret-key}
server.port=8086
logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true